source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
workspace './GoogleMaterialIconFont.xcworkspace'

target 'GoogleMaterialIconFont_Example' do
  pod "GoogleMaterialIconFont", :path => "../"
end

target 'GoogleMaterialIconFont_Tests' do
  pod "GoogleMaterialIconFont", :path => "../"
end
