//
//  Font.swift
//  Pods
//
//  Created by Yusuke Kita on 9/23/15.
//
//

@objc public enum MaterialIconFont: Int {
    case ThreeDRotation
    case AccessAlarm
    case AccessAlarms
    case AccessTime
    case Accessibility
    case AccountBalanceWallet
    case AccountBalance
    case AccountBox
    case AccountCircle
    case Adb
    case AddAlarm
    case AddAlert
    case AddBox
    case AddCircleOutline
    case AddCircle
    case AddShoppingCart
    case AddToPhotos
    case Add
    case Adjust
    case AirlineSeatFlatAngled
    case AirlineSeatFlat
    case AirlineSeatIndividualSuite
    case AirlineSeatLegroomExtra
    case AirlineSeatLegroomNormal
    case AirlineSeatLegroomReduced
    case AirlineSeatReclineExtra
    case AirlineSeatReclineNormal
    case AirplanemodeActive
    case AirplanemodeInactive
    case Airplay
    case AlarmAdd
    case AlarmOff
    case AlarmOn
    case Alarm
    case Album
    case Android
    case Announcement
    case Apps
    case Archive
    case ArrowBack
    case ArrowDropDownCircle
    case ArrowDropDown
    case ArrowDropUp
    case ArrowForward
    case AspectRatio
    case Assessment
    case AssignmentInd
    case AssignmentLate
    case AssignmentReturn
    case AssignmentReturned
    case AssignmentTurnedIn
    case Assignment
    case AssistantPhoto
    case Assistant
    case AttachFile
    case AttachMoney
    case Attachment
    case Audiotrack
    case Autorenew
    case AvTimer
    case Backspace
    case Backup
    case Battery20
    case Battery30
    case Battery50
    case Battery60
    case Battery80
    case Battery90
    case BatteryAlert
    case BatteryCharging20
    case BatteryCharging30
    case BatteryCharging50
    case BatteryCharging60
    case BatteryCharging80
    case BatteryCharging90
    case BatteryChargingFull
    case BatteryFull
    case BatteryStd
    case BatteryUnknown
    case Beenhere
    case Block
    case BluetoothAudio
    case BluetoothConnected
    case BluetoothDisabled
    case BluetoothSearching
    case Bluetooth
    case BlurCircular
    case BlurLinear
    case BlurOff
    case BlurOn
    case Book
    case BookmarkBorder
    case Bookmark
    case BorderAll
    case BorderBottom
    case BorderClear
    case BorderColor
    case BorderHorizontal
    case BorderInner
    case BorderLeft
    case BorderOuter
    case BorderRight
    case BorderStyle
    case BorderTop
    case BorderVertical
    case Brightness1
    case Brightness2
    case Brightness3
    case Brightness4
    case Brightness5
    case Brightness6
    case Brightness7
    case BrightnessAuto
    case BrightnessHigh
    case BrightnessLow
    case BrightnessMedium
    case BrokenImage
    case Brush
    case BugReport
    case Build
    case Business
    case Cached
    case Cake
    case Call
    case CallEnd
    case CallMade
    case CallMerge
    case CallMissed
    case CallReceived
    case CallSplit
    case CameraAlt
    case CameraEnhance
    case CameraFront
    case CameraRear
    case CameraRoll
    case Camera
    case Cancel
    case CardGiftcard
    case CardMembership
    case CardTravel
    case CastConnected
    case Cast
    case CenterFocusStrong
    case CenterFocusWeak
    case ChangeHistory
    case ChatBubble
    case ChatBubbleOutline
    case Chat
    case CheckBox
    case CheckBoxOutlineBlank
    case CheckCircle
    case Check
    case ChevronLeft
    case ChevronRight
    case ChromeReaderMode
    case Class
    case ClearAll
    case Clear
    case ClosedCaption
    case Close
    case CloudCircle
    case CloudDone
    case CloudDownload
    case CloudOff
    case CloudQueue
    case CloudUpload
    case Cloud
    case Code
    case CollectionsBookmark
    case Collections
    case Colorize
    case ColorLens
    case Comment
    case Compare
    case Computer
    case ConfirmationNumber
    case ContactPhone
    case Contacts
    case ContentCopy
    case ContentCut
    case ContentPaste
    case ControlPoint
    case ControlPointDuplicate
    case Create
    case CreditCard
    case Crop169
    case Crop32
    case Crop54
    case Crop75
    case CropDin
    case CropFree
    case CropLandscape
    case CropOriginal
    case CropPortrait
    case CropSquare
    case Crop
    case Dashboard
    case DataUsage
    case Dehaze
    case Delete
    case Description
    case DesktopMac
    case DesktopWindows
    case Details
    case DeveloperBoard
    case DeveloperMode
    case DeviceHub
    case Devices
    case DialerSip
    case Dialpad
    case DirectionsBike
    case DirectionsBoat
    case DirectionsBus
    case DirectionsCar
    case DirectionsRailway
    case DirectionsRun
    case DirectionsSubway
    case DirectionsTransit
    case DirectionsWalk
    case Directions
    case DiscFull
    case Dns
    case Dock
    case Domain
    case Done
    case DoneAll
    case DoNotDisturbAlt
    case DoNotDisturb
    case Drafts
    case DriveEta
    case Dvr
    case Edit
    case Eject
    case Email
    case Equalizer
    case ErrorOutline
    case Error
    case EventAvailable
    case EventBusy
    case EventNote
    case EventSeat
    case Event
    case ExitToApp
    case ExpandLess
    case ExpandMore
    case Explicit
    case Explore
    case ExposureNeg1
    case ExposureNeg2
    case ExposurePlus1
    case ExposurePlus2
    case ExposureZero
    case Exposure
    case Extension
    case FastForward
    case FastRewind
    case Face
    case FavoriteBorder
    case Favorite
    case Feedback
    case FileDownload
    case FileUpload
    case Filter1
    case Filter2
    case Filter3
    case Filter4
    case Filter5
    case Filter6
    case Filter7
    case Filter8
    case Filter9
    case Filter9Plus
    case FilterBAndW
    case FilterCenterFocus
    case FilterDrama
    case FilterFrames
    case FilterHdr
    case FilterList
    case FilterNone
    case FilterTiltShift
    case FilterVintage
    case Filter
    case FindInPage
    case FindReplace
    case Flag
    case Flare
    case FlashAuto
    case FlashOff
    case FlashOn
    case FlightLand
    case FlightTakeoff
    case Flight
    case FlipToBack
    case FlipToFront
    case Flip
    case FolderOpen
    case FolderShared
    case FolderSpecial
    case Folder
    case FontDownload
    case FormatAlignCenter
    case FormatAlignJustify
    case FormatAlignLeft
    case FormatAlignRight
    case FormatBold
    case FormatClear
    case FormatColorFill
    case FormatColorReset
    case FormatColorText
    case FormatIndentDecrease
    case FormatIndentIncrease
    case FormatItalic
    case FormatLineSpacing
    case FormatListBulleted
    case FormatListNumbered
    case FormatPaint
    case FormatQuote
    case FormatSize
    case FormatStrikethrough
    case FormatTextdirectionLToR
    case FormatTextdirectionRToL
    case FormatUnderlined
    case Forum
    case Forward10
    case Forward30
    case Forward5
    case Forward
    case Fullscreen
    case FullscreenExit
    case Functions
    case Gamepad
    case Games
    case Gesture
    case GetApp
    case Gif
    case GpsFixed
    case GpsNotFixed
    case GpsOff
    case Grade
    case Gradient
    case Grain
    case GraphicEq
    case GridOff
    case GridOn
    case GroupAdd
    case GroupWork
    case Group
    case Hd
    case HdrOff
    case HdrOn
    case HdrStrong
    case HdrWeak
    case Headset
    case HeadsetMic
    case Healing
    case Hearing
    case HelpOutline
    case Help
    case HighlightOff
    case HighQuality
    case History
    case Home
    case Hotel
    case HourglassEmpty
    case HourglassFull
    case Http
    case Https
    case ImageAspectRatio
    case Image
    case ImportExport
    case Inbox
    case IndeterminateCheckBox
    case InfoOutline
    case Info
    case Input
    case InsertChart
    case InsertComment
    case InsertDriveFile
    case InsertEmoticon
    case InsertInvitation
    case InsertLink
    case InsertPhoto
    case InvertColors
    case InvertColorsOff
    case Iso
    case KeyboardArrowDown
    case KeyboardArrowLeft
    case KeyboardArrowRight
    case KeyboardArrowUp
    case KeyboardBackspace
    case KeyboardCapslock
    case KeyboardHide
    case KeyboardReturn
    case KeyboardTab
    case KeyboardVoice
    case Keyboard
    case LabelOutline
    case Label
    case Landscape
    case Language
    case LaptopChromebook
    case Laptop
    case LaptopMac
    case LaptopWindows
    case Launch
    case Layers
    case LayersClear
    case LeakAdd
    case LeakRemove
    case Lens
    case LibraryAdd
    case LibraryBooks
    case LibraryMusic
    case Link
    case List
    case LiveHelp
    case LiveTv
    case LocalActivity
    case LocalAirport
    case LocalAtm
    case LocalBar
    case LocalCafe
    case LocalCarWash
    case LocalConvenienceStore
    case LocalDining
    case LocalDrink
    case LocalFlorist
    case LocalGasStation
    case LocalGroceryStore
    case LocalHospital
    case LocalHotel
    case LocalLaundryService
    case LocalLibrary
    case LocalMall
    case LocalMovies
    case LocalOffer
    case LocalParking
    case LocalPharmacy
    case LocalPhone
    case LocalPizza
    case LocalPlay
    case LocalPostOffice
    case LocalPrintshop
    case LocalSee
    case LocalShipping
    case LocalTaxi
    case LocationCity
    case LocationDisabled
    case LocationOff
    case LocationOn
    case LocationSearching
    case LockOpen
    case LockOutline
    case Lock
    case Looks3
    case Looks4
    case Looks5
    case Looks6
    case LooksOne
    case LooksTwo
    case Looks
    case Loop
    case Loupe
    case Loyalty
    case Mail
    case Map
    case MarkunreadMailbox
    case Markunread
    case Memory
    case Menu
    case MergeType
    case Message
    case Mic
    case MicNone
    case MicOff
    case Mms
    case ModeComment
    case ModeEdit
    case MoneyOff
    case MonochromePhotos
    case MoodBad
    case Mood
    case MoreHoriz
    case MoreVert
    case More
    case Mouse
    case MovieCreation
    case Movie
    case MusicNote
    case MyLocation
    case NaturePeople
    case Nature
    case NavigateBefore
    case NavigateNext
    case Navigation
    case NetworkCell
    case NetworkLocked
    case NetworkWifi
    case NewReleases
    case Nfc
    case NoSim
    case NotInterested
    case NoteAdd
    case NotificationsActive
    case NotificationsNone
    case NotificationsOff
    case NotificationsPaused
    case Notifications
    case OfflinePin
    case OndemandVideo
    case OpenInBrowser
    case OpenInNew
    case OpenWith
    case Pages
    case Pageview
    case Palette
    case PanoramaFishEye
    case PanoramaHorizontal
    case PanoramaVertical
    case PanoramaWideAngle
    case Panorama
    case PartyMode
    case PauseCircleFilled
    case PauseCircleOutline
    case Pause
    case Payment
    case PeopleOutline
    case People
    case PermCameraMic
    case PermContactCalendar
    case PermDataSetting
    case PermDeviceInformation
    case PermIdentity
    case PermMedia
    case PermPhoneMsg
    case PermScanWifi
    case PersonAdd
    case PersonalVideo
    case PersonOutline
    case PersonPin
    case Person
    case PhoneAndroid
    case PhoneBluetoothSpeaker
    case PhoneForwarded
    case PhoneInTalk
    case PhoneIphone
    case Phonelink
    case PhonelinkErase
    case PhonelinkLock
    case PhonelinkOff
    case PhonelinkRing
    case PhonelinkSetup
    case PhoneLocked
    case PhoneMissed
    case PhonePaused
    case Phone
    case PhotoAlbum
    case PhotoCamera
    case PhotoLibrary
    case PhotoSizeSelectActual
    case PhotoSizeSelectLarge
    case PhotoSizeSelectSmall
    case Photo
    case PictureAsPdf
    case PictureInPicture
    case PinDrop
    case Place
    case PlayArrow
    case PlayCircleFilled
    case PlayCircleOutline
    case PlayForWork
    case PlaylistAdd
    case PlusOne
    case Poll
    case Polymer
    case PortableWifiOff
    case Portrait
    case Power
    case PowerInput
    case PowerSettingsNew
    case PresentToAll
    case Print
    case Public
    case Publish
    case QueryBuilder
    case QuestionAnswer
    case QueueMusic
    case Queue
    case RadioButtonChecked
    case RadioButtonUnchecked
    case Radio
    case RateReview
    case Receipt
    case RecentActors
    case Redeem
    case Redo
    case Refresh
    case RemoveCircle
    case RemoveCircleOutline
    case RemoveRedEye
    case Remove
    case Reorder
    case Repeat
    case RepeatOne
    case Replay10
    case Replay30
    case Replay5
    case Replay
    case ReplyAll
    case Reply
    case ReportProblem
    case Report
    case RestaurantMenu
    case Restore
    case RingVolume
    case Room
    case Rotate90DegreesCcw
    case RotateLeft
    case RotateRight
    case Router
    case Satellite
    case Save
    case Scanner
    case Schedule
    case School
    case ScreenLockLandscape
    case ScreenLockPortrait
    case ScreenLockRotation
    case ScreenRotation
    case SdCard
    case SdStorage
    case Search
    case Security
    case SelectAll
    case Send
    case SettingsApplications
    case SettingsBackupRestore
    case SettingsBluetooth
    case SettingsBrightness
    case SettingsCell
    case SettingsEthernet
    case SettingsInputAntenna
    case SettingsInputComponent
    case SettingsInputComposite
    case SettingsInputHdmi
    case SettingsInputSvideo
    case SettingsOverscan
    case SettingsPhone
    case SettingsPower
    case SettingsRemote
    case SettingsSystemDaydream
    case SettingsVoice
    case Settings
    case Share
    case Shop
    case ShoppingBasket
    case ShoppingCart
    case ShopTwo
    case Shuffle
    case SignalCellular0Bar
    case SignalCellular1Bar
    case SignalCellular2Bar
    case SignalCellular3Bar
    case SignalCellular4Bar
    case SignalCellularConnectedNoInternet0Bar
    case SignalCellularConnectedNoInternet1Bar
    case SignalCellularConnectedNoInternet2Bar
    case SignalCellularConnectedNoInternet3Bar
    case SignalCellularConnectedNoInternet4Bar
    case SignalCellularNoSim
    case SignalCellularNull
    case SignalCellularOff
    case SignalWifi0Bar
    case SignalWifi1Bar
    case SignalWifi1BarLock
    case SignalWifi2Bar
    case SignalWifi2BarLock
    case SignalWifi3Bar
    case SignalWifi3BarLock
    case SignalWifi4Bar
    case SignalWifi4BarLock
    case SignalWifiOff
    case SignalWifiStatusbar1Bar26
    case SignalWifiStatusbar2Bar26
    case SignalWifiStatusbar3Bar26
    case SignalWifiStatusbar4Bar26
    case SignalWifiStatusbarConnectedNoInternet126
    case SignalWifiStatusbarConnectedNoInternet226
    case SignalWifiStatusbarConnectedNoInternet26
    case SignalWifiStatusbarConnectedNoInternet326
    case SignalWifiStatusbarConnectedNoInternet426
    case SignalWifiStatusbarNotConnected26
    case SignalWifiStatusbarNull26
    case SimCardAlert
    case SimCard
    case SkipNext
    case SkipPrevious
    case Slideshow
    case Smartphone
    case SmsFailed
    case Sms
    case Snooze
    case SortByAlpha
    case Sort
    case SpaceBar
    case Speaker
    case SpeakerGroup
    case SpeakerNotes
    case SpeakerPhone
    case Spellcheck
    case StarBorder
    case StarHalf
    case Star
    case Stars
    case StayCurrentLandscape
    case StayCurrentPortrait
    case StayPrimaryLandscape
    case StayPrimaryPortrait
    case Stop
    case Storage
    case StoreMallDirectory
    case Store
    case Straighten
    case StrikethroughS
    case Style
    case Subject
    case Subtitles
    case SupervisorAccount
    case SurroundSound
    case SwapCalls
    case SwapHoriz
    case SwapVert
    case SwapVerticalCircle
    case SwitchCamera
    case SwitchVideo
    case SyncDisabled
    case SyncProblem
    case Sync
    case SystemUpdate
    case SystemUpdateAlt
    case Tab
    case TabletAndroid
    case TabletMac
    case Tablet
    case TabUnselected
    case TactMail
    case TagFaces
    case TapAndPlay
    case Terrain
    case TextFormat
    case Textsms
    case Texture
    case Theaters
    case ThumbDown
    case ThumbsUpDown
    case ThumbUp
    case Timelapse
    case Timer10
    case Timer3
    case TimerOff
    case Timer
    case TimeToLeave
    case Toc
    case Today
    case Toll
    case Tonality
    case Toys
    case TrackChanges
    case Traffic
    case Transform
    case Translate
    case TrendingDown
    case TrendingFlat
    case TrendingUp
    case Tune
    case TurnedIn
    case TurnedInNot
    case Tv
    case Undo
    case UnfoldLess
    case UnfoldMore
    case Usb
    case VerifiedUser
    case VerticalAlignBottom
    case VerticalAlignCenter
    case VerticalAlignTop
    case Vibration
    case VideocamOff
    case Videocam
    case VideoLibrary
    case ViewAgenda
    case ViewArray
    case ViewCarousel
    case ViewColumn
    case ViewComfy
    case ViewCompact
    case ViewDay
    case ViewHeadline
    case ViewList
    case ViewModule
    case ViewQuilt
    case ViewStream
    case ViewWeek
    case Vignette
    case VisibilityOff
    case Visibility
    case VoiceChat
    case Voicemail
    case VolumeDown
    case VolumeMute
    case VolumeOff
    case VolumeUp
    case VpnKey
    case VpnLock
    case Wallpaper
    case Warning
    case Watch
    case WbAuto
    case WbCloudy
    case WbIncandescent
    case WbIridescent
    case WbSunny
    case Wc
    case Web
    case Whatshot
    case Widgets
    case WifiLock
    case WifiTethering
    case Wifi
    case Work
    case WrapText
    case YoutubeSearchedFor
    case ZoomIn
    case ZoomOut
}

internal struct IconFont {
    static let codes = [
        "\u{e600}", "\u{e601}", "\u{e602}", "\u{e603}", "\u{e604}", "\u{e605}", "\u{e606}", "\u{e607}", "\u{e608}", "\u{e609}", "\u{e60a}", "\u{e60b}", "\u{e60c}", "\u{e60d}", "\u{e60e}", "\u{e60f}", "\u{e610}", "\u{e611}", "\u{e612}", "\u{e613}", "\u{e614}", "\u{e615}", "\u{e616}", "\u{e617}", "\u{e618}", "\u{e619}", "\u{e61a}", "\u{e61b}", "\u{e61c}", "\u{e61d}", "\u{e61e}", "\u{e61f}", "\u{e620}", "\u{e621}", "\u{e622}", "\u{e623}", "\u{e624}", "\u{e625}", "\u{e626}", "\u{e627}", "\u{e628}", "\u{e629}", "\u{e62a}", "\u{e62b}", "\u{e62c}", "\u{e62d}", "\u{e62e}", "\u{e62f}", "\u{e630}", "\u{e631}", "\u{e632}", "\u{e633}", "\u{e634}", "\u{e635}", "\u{e636}", "\u{e637}", "\u{e638}", "\u{e639}", "\u{e63a}", "\u{e63b}", "\u{e63c}", "\u{e63d}", "\u{e63e}", "\u{e63f}", "\u{e640}", "\u{e641}", "\u{e642}", "\u{e643}", "\u{e644}", "\u{e645}", "\u{e646}", "\u{e647}", "\u{e648}", "\u{e649}", "\u{e64a}", "\u{e64b}", "\u{e64c}", "\u{e64d}", "\u{e64e}", "\u{e64f}", "\u{e650}", "\u{e651}", "\u{e652}", "\u{e653}", "\u{e654}", "\u{e655}", "\u{e656}", "\u{e657}", "\u{e658}", "\u{e659}", "\u{e65a}", "\u{e65b}", "\u{e65c}", "\u{e65d}", "\u{e65e}", "\u{e65f}", "\u{e660}", "\u{e661}", "\u{e662}", "\u{e663}", "\u{e664}", "\u{e665}", "\u{e666}", "\u{e667}", "\u{e668}", "\u{e669}", "\u{e66a}", "\u{e66b}", "\u{e66c}", "\u{e66d}", "\u{e66e}", "\u{e66f}", "\u{e670}", "\u{e671}", "\u{e672}", "\u{e673}", "\u{e674}", "\u{e675}", "\u{e676}", "\u{e677}", "\u{e678}", "\u{e679}", "\u{e67a}", "\u{e67b}", "\u{e67c}", "\u{e67d}", "\u{e67e}", "\u{e67f}", "\u{e680}", "\u{e681}", "\u{e682}", "\u{e683}", "\u{e684}", "\u{e685}", "\u{e686}", "\u{e687}", "\u{e688}", "\u{e689}", "\u{e68a}", "\u{e68b}", "\u{e68c}", "\u{e68d}", "\u{e68e}", "\u{e68f}", "\u{e690}", "\u{e691}", "\u{e692}", "\u{e693}", "\u{e694}", "\u{e695}", "\u{e696}", "\u{e697}", "\u{e698}", "\u{e699}", "\u{e69a}", "\u{e69b}", "\u{e69c}", "\u{e69d}", "\u{e69e}", "\u{e69f}", "\u{e6a0}", "\u{e6a1}", "\u{e6a2}", "\u{e6a3}", "\u{e6a4}", "\u{e6a5}", "\u{e6a6}", "\u{e6a7}", "\u{e6a8}", "\u{e6a9}", "\u{e6aa}", "\u{e6ab}", "\u{e6ac}", "\u{e6ad}", "\u{e6ae}", "\u{e6af}", "\u{e6b0}", "\u{e6b1}", "\u{e6b2}", "\u{e6b3}", "\u{e6b4}", "\u{e6b5}", "\u{e6b6}", "\u{e6b7}", "\u{e6b8}", "\u{e6b9}", "\u{e6ba}", "\u{e6bb}", "\u{e6bc}", "\u{e6bd}", "\u{e6be}", "\u{e6bf}", "\u{e6c0}", "\u{e6c1}", "\u{e6c2}", "\u{e6c3}", "\u{e6c4}", "\u{e6c5}", "\u{e6c6}", "\u{e6c7}", "\u{e6c8}", "\u{e6c9}", "\u{e6ca}", "\u{e6cb}", "\u{e6cc}", "\u{e6cd}", "\u{e6ce}", "\u{e6cf}", "\u{e6d0}", "\u{e6d1}", "\u{e6d2}", "\u{e6d3}", "\u{e6d4}", "\u{e6d5}", "\u{e6d6}", "\u{e6d7}", "\u{e6d8}", "\u{e6d9}", "\u{e6da}", "\u{e6db}", "\u{e6dc}", "\u{e6dd}", "\u{e6de}", "\u{e6df}", "\u{e6e0}", "\u{e6e1}", "\u{e6e2}", "\u{e6e3}", "\u{e6e4}", "\u{e6e5}", "\u{e6e6}", "\u{e6e7}", "\u{e6e8}", "\u{e6e9}", "\u{e6ea}", "\u{e6eb}", "\u{e6ec}", "\u{e6ed}", "\u{e6ee}", "\u{e6ef}", "\u{e6f0}", "\u{e6f1}", "\u{e6f2}", "\u{e6f3}", "\u{e6f4}", "\u{e6f5}", "\u{e6f6}", "\u{e6f7}", "\u{e6f8}", "\u{e6f9}", "\u{e6fa}", "\u{e6fb}", "\u{e6fc}", "\u{e6fd}", "\u{e6fe}", "\u{e6ff}", "\u{e700}", "\u{e701}", "\u{e702}", "\u{e703}", "\u{e704}", "\u{e705}", "\u{e706}", "\u{e707}", "\u{e708}", "\u{e709}", "\u{e70a}", "\u{e70b}", "\u{e70c}", "\u{e70d}", "\u{e70e}", "\u{e70f}", "\u{e710}", "\u{e711}", "\u{e712}", "\u{e713}", "\u{e714}", "\u{e715}", "\u{e716}", "\u{e717}", "\u{e718}", "\u{e719}", "\u{e71a}", "\u{e71b}", "\u{e71c}", "\u{e71d}", "\u{e71e}", "\u{e71f}", "\u{e720}", "\u{e721}", "\u{e722}", "\u{e723}", "\u{e724}", "\u{e725}", "\u{e726}", "\u{e727}", "\u{e728}", "\u{e729}", "\u{e72a}", "\u{e72b}", "\u{e72c}", "\u{e72d}", "\u{e72e}", "\u{e72f}", "\u{e730}", "\u{e731}", "\u{e732}", "\u{e733}", "\u{e734}", "\u{e735}", "\u{e736}", "\u{e737}", "\u{e738}", "\u{e739}", "\u{e73a}", "\u{e73b}", "\u{e73c}", "\u{e73d}", "\u{e73e}", "\u{e73f}", "\u{e740}", "\u{e741}", "\u{e742}", "\u{e743}", "\u{e744}", "\u{e745}", "\u{e746}", "\u{e747}", "\u{e748}", "\u{e749}", "\u{e74a}", "\u{e74b}", "\u{e74c}", "\u{e74d}", "\u{e74e}", "\u{e74f}", "\u{e750}", "\u{e751}", "\u{e752}", "\u{e753}", "\u{e754}", "\u{e755}", "\u{e756}", "\u{e757}", "\u{e758}", "\u{e759}", "\u{e75a}", "\u{e75b}", "\u{e75c}", "\u{e75d}", "\u{e75e}", "\u{e75f}", "\u{e760}", "\u{e761}", "\u{e762}", "\u{e763}", "\u{e764}", "\u{e765}", "\u{e766}", "\u{e767}", "\u{e768}", "\u{e769}", "\u{e76a}", "\u{e76b}", "\u{e76c}", "\u{e76d}", "\u{e76e}", "\u{e76f}", "\u{e770}", "\u{e771}", "\u{e772}", "\u{e773}", "\u{e774}", "\u{e775}", "\u{e776}", "\u{e777}", "\u{e778}", "\u{e779}", "\u{e77a}", "\u{e77b}", "\u{e77c}", "\u{e77d}", "\u{e77e}", "\u{e77f}", "\u{e780}", "\u{e781}", "\u{e782}", "\u{e783}", "\u{e784}", "\u{e785}", "\u{e786}", "\u{e787}", "\u{e788}", "\u{e789}", "\u{e78a}", "\u{e78b}", "\u{e78c}", "\u{e78d}", "\u{e78e}", "\u{e78f}", "\u{e790}", "\u{e791}", "\u{e792}", "\u{e793}", "\u{e794}", "\u{e795}", "\u{e796}", "\u{e797}", "\u{e798}", "\u{e799}", "\u{e79a}", "\u{e79b}", "\u{e79c}", "\u{e79d}", "\u{e79e}", "\u{e79f}", "\u{e7a0}", "\u{e7a1}", "\u{e7a2}", "\u{e7a3}", "\u{e7a4}", "\u{e7a5}", "\u{e7a6}", "\u{e7a7}", "\u{e7a8}", "\u{e7a9}", "\u{e7aa}", "\u{e7ab}", "\u{e7ac}", "\u{e7ad}", "\u{e7ae}", "\u{e7af}", "\u{e7b0}", "\u{e7b1}", "\u{e7b2}", "\u{e7b3}", "\u{e7b4}", "\u{e7b5}", "\u{e7b6}", "\u{e7b7}", "\u{e7b8}", "\u{e7b9}", "\u{e7ba}", "\u{e7bb}", "\u{e7bc}", "\u{e7bd}", "\u{e7be}", "\u{e7bf}", "\u{e7c0}", "\u{e7c1}", "\u{e7c2}", "\u{e7c3}", "\u{e7c4}", "\u{e7c5}", "\u{e7c6}", "\u{e7c7}", "\u{e7c8}", "\u{e7c9}", "\u{e7ca}", "\u{e7cb}", "\u{e7cc}", "\u{e7cd}", "\u{e7ce}", "\u{e7cf}", "\u{e7d0}", "\u{e7d1}", "\u{e7d2}", "\u{e7d3}", "\u{e7d4}", "\u{e7d5}", "\u{e7d6}", "\u{e7d7}", "\u{e7d8}", "\u{e7d9}", "\u{e7da}", "\u{e7db}", "\u{e7dc}", "\u{e7dd}", "\u{e7de}", "\u{e7df}", "\u{e7e0}", "\u{e7e1}", "\u{e7e2}", "\u{e7e3}", "\u{e7e4}", "\u{e7e5}", "\u{e7e6}", "\u{e7e7}", "\u{e7e8}", "\u{e7e9}", "\u{e7ea}", "\u{e7eb}", "\u{e7ec}", "\u{e7ed}", "\u{e7ee}", "\u{e7ef}", "\u{e7f0}", "\u{e7f1}", "\u{e7f2}", "\u{e7f3}", "\u{e7f4}", "\u{e7f5}", "\u{e7f6}", "\u{e7f7}", "\u{e7f8}", "\u{e7f9}", "\u{e7fa}", "\u{e7fb}", "\u{e7fc}", "\u{e7fd}", "\u{e7fe}", "\u{e7ff}", "\u{e800}", "\u{e801}", "\u{e802}", "\u{e803}", "\u{e804}", "\u{e805}", "\u{e806}", "\u{e807}", "\u{e808}", "\u{e809}", "\u{e80a}", "\u{e80b}", "\u{e80c}", "\u{e80d}", "\u{e80e}", "\u{e80f}", "\u{e810}", "\u{e811}", "\u{e812}", "\u{e813}", "\u{e814}", "\u{e815}", "\u{e816}", "\u{e817}", "\u{e818}", "\u{e819}", "\u{e81a}", "\u{e81b}", "\u{e81c}", "\u{e81d}", "\u{e81e}", "\u{e81f}", "\u{e820}", "\u{e821}", "\u{e822}", "\u{e823}", "\u{e824}", "\u{e825}", "\u{e826}", "\u{e827}", "\u{e828}", "\u{e829}", "\u{e82a}", "\u{e82b}", "\u{e82c}", "\u{e82d}", "\u{e82e}", "\u{e82f}", "\u{e830}", "\u{e831}", "\u{e832}", "\u{e833}", "\u{e834}", "\u{e835}", "\u{e836}", "\u{e837}", "\u{e838}", "\u{e839}", "\u{e83a}", "\u{e83b}", "\u{e83c}", "\u{e83d}", "\u{e83e}", "\u{e83f}", "\u{e840}", "\u{e841}", "\u{e842}", "\u{e843}", "\u{e844}", "\u{e845}", "\u{e846}", "\u{e847}", "\u{e848}", "\u{e849}", "\u{e84a}", "\u{e84b}", "\u{e84c}", "\u{e84d}", "\u{e84e}", "\u{e84f}", "\u{e850}", "\u{e851}", "\u{e852}", "\u{e853}", "\u{e854}", "\u{e855}", "\u{e856}", "\u{e857}", "\u{e858}", "\u{e859}", "\u{e85a}", "\u{e85b}", "\u{e85c}", "\u{e85d}", "\u{e85e}", "\u{e85f}", "\u{e860}", "\u{e861}", "\u{e862}", "\u{e863}", "\u{e864}", "\u{e865}", "\u{e866}", "\u{e867}", "\u{e868}", "\u{e869}", "\u{e86a}", "\u{e86b}", "\u{e86c}", "\u{e86d}", "\u{e86e}", "\u{e86f}", "\u{e870}", "\u{e871}", "\u{e872}", "\u{e873}", "\u{e874}", "\u{e875}", "\u{e876}", "\u{e877}", "\u{e878}", "\u{e879}", "\u{e87a}", "\u{e87b}", "\u{e87c}", "\u{e87d}", "\u{e87e}", "\u{e87f}", "\u{e880}", "\u{e881}", "\u{e882}", "\u{e883}", "\u{e884}", "\u{e885}", "\u{e886}", "\u{e887}", "\u{e888}", "\u{e889}", "\u{e88a}", "\u{e88b}", "\u{e88c}", "\u{e88d}", "\u{e88e}", "\u{e88f}", "\u{e890}", "\u{e891}", "\u{e892}", "\u{e893}", "\u{e894}", "\u{e895}", "\u{e896}", "\u{e897}", "\u{e898}", "\u{e899}", "\u{e89a}", "\u{e89b}", "\u{e89c}", "\u{e89d}", "\u{e89e}", "\u{e89f}", "\u{e8a0}", "\u{e8a1}", "\u{e8a2}", "\u{e8a3}", "\u{e8a4}", "\u{e8a5}", "\u{e8a6}", "\u{e8a7}", "\u{e8a8}", "\u{e8a9}", "\u{e8aa}", "\u{e8ab}", "\u{e8ac}", "\u{e8ad}", "\u{e8ae}", "\u{e8af}", "\u{e8b0}", "\u{e8b1}", "\u{e8b2}", "\u{e8b3}", "\u{e8b4}", "\u{e8b5}", "\u{e8b6}", "\u{e8b7}", "\u{e8b8}", "\u{e8b9}", "\u{e8ba}", "\u{e8bb}", "\u{e8bc}", "\u{e8bd}", "\u{e8be}", "\u{e8bf}", "\u{e8c0}", "\u{e8c1}", "\u{e8c2}", "\u{e8c3}", "\u{e8c4}", "\u{e8c5}", "\u{e8c6}", "\u{e8c7}", "\u{e8c8}", "\u{e8c9}", "\u{e8ca}", "\u{e8cb}", "\u{e8cc}", "\u{e8cd}", "\u{e8ce}", "\u{e8cf}", "\u{e8d0}", "\u{e8d1}", "\u{e8d2}", "\u{e8d3}", "\u{e8d4}", "\u{e8d5}", "\u{e8d6}", "\u{e8d7}", "\u{e8d8}", "\u{e8d9}", "\u{e8da}", "\u{e8db}", "\u{e8dc}", "\u{e8dd}", "\u{e8de}", "\u{e8df}", "\u{e8e0}", "\u{e8e1}", "\u{e8e2}", "\u{e8e3}", "\u{e8e4}", "\u{e8e5}", "\u{e8e6}", "\u{e8e7}", "\u{e8e8}", "\u{e8e9}", "\u{e8ea}", "\u{e8eb}", "\u{e8ec}", "\u{e8ed}", "\u{e8ee}", "\u{e8ef}", "\u{e8f0}", "\u{e8f1}", "\u{e8f2}", "\u{e8f3}", "\u{e8f4}", "\u{e8f5}", "\u{e8f6}", "\u{e8f7}", "\u{e8f8}", "\u{e8f9}", "\u{e8fa}", "\u{e8fb}", "\u{e8fc}", "\u{e8fd}", "\u{e8fe}", "\u{e8ff}", "\u{e900}", "\u{e901}", "\u{e902}", "\u{e903}", "\u{e904}", "\u{e905}", "\u{e906}", "\u{e907}", "\u{e908}", "\u{e909}", "\u{e90a}", "\u{e90b}", "\u{e90c}", "\u{e90d}", "\u{e90e}", "\u{e90f}", "\u{e910}", "\u{e911}", "\u{e912}", "\u{e913}", "\u{e914}", "\u{e915}", "\u{e916}", "\u{e917}", "\u{e918}", "\u{e919}", "\u{e91a}", "\u{e91b}", "\u{e91c}", "\u{e91d}", "\u{e91e}", "\u{e91f}", "\u{e920}", "\u{e921}", "\u{e922}", "\u{e923}", "\u{e924}", "\u{e925}", "\u{e926}", "\u{e927}", "\u{e928}", "\u{e929}", "\u{e92a}", "\u{e92b}", "\u{e92c}", "\u{e92d}", "\u{e92e}", "\u{e92f}", "\u{e930}", "\u{e931}", "\u{e932}", "\u{e933}", "\u{e934}", "\u{e935}", "\u{e936}", "\u{e937}", "\u{e938}", "\u{e939}", "\u{e93a}", "\u{e93b}", "\u{e93c}", "\u{e93d}", "\u{e93e}", "\u{e93f}", "\u{e940}", "\u{e941}"
    ]
}